drop table t_alumnes if exists
drop table t_cursos if exists
drop table t_matricules if exists
create table t_alumnes (alu_nom varchar(255) not null, alu_edat integer, primary key (alu_nom))
create table t_cursos (cur_nom varchar(255) not null, cur_edatminima integer, primary key (cur_nom))
create table t_matricules (mat_id bigint generated by default as identity, mat_alumne varchar(255), mat_curs varchar(255), primary key (mat_id))
alter table t_matricules add constraint matricula_alumne_fk foreign key (mat_alumne) references t_alumnes
alter table t_matricules add constraint matricula_curs_fk foreign key (mat_curs) references t_cursos
