drop table if exists t_municipis;
drop table if exists t_persones;
create table t_municipis (mun_id int generated by default as identity, mun_nom varchar(255), primary key (mun_id));
create table t_persones (per_id int generated by default as identity, per_nom varchar(255), per_munid bigint, primary key (per_id));
alter table t_persones add constraint permun_fk foreign key (per_munid) references t_municipis;