create table t_illes (ill_nom varchar(255), primary key (ill_nom));
create table t_municipis (mun_id int generated by default as identity, mun_nom varchar(255), mun_illa varchar(255), primary key (mun_id));
create table t_persones (per_id int generated by default as identity, per_nom varchar(255), per_edat int, per_munid bigint, primary key (per_id));
alter table t_municipis add constraint munilla_fk foreign key (mun_illa) references t_illes;
alter table t_persones add constraint permun_fk foreign key (per_munid) references t_municipis;